version: '3.3'
services:
  db_test:
    image: mariadb:latest
    volumes:
      - ramdisk_test:/var/lib/mysql:rw
      - ./database/docker/init:/docker-entrypoint-initdb.d
      - ./database/docker/my-test.cnf:/etc/mysql/conf.d/.my.cnf:ro
    ports:
      - "3311:3306"
    environment:
      - MYSQL_DATABASE=app_test
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
volumes:
  ramdisk_test:
    driver_opts:
      type: tmpfs
      device: tmpfs