version: '3.3'
services:
  backend:
    build:
      context: app/docker
    user: user
    volumes:
      - ./app/code:/var/www:cached
      - ./app/docker/init.sh:/docker-init/init.sh
      - ./app/docker/ini/php.ini:/usr/local/etc/php/php.ini
      - ./app/docker/ini/php-cli.ini:/usr/local/etc/php/php-cli.ini
      - ./app/docker/ini/zcustom-fpm.conf:/usr/local/etc/php-fpm.d/zcustom-fpm.conf
  nginx:
    image: nginx:latest
    environment:
      APP_HOST: 'backend'
    ports:
      # external:in-container
      - "8080:80"
    volumes:
      - ./app/code/public:/var/www:cached
      - ./nginx/docker/conf/nginx.conf:/etc/nginx/templates/default.conf.template
    links:
      - backend
  db:
    image: mariadb:latest
    volumes:
      - ./database/docker/init:/docker-entrypoint-initdb.d
      - ./database/docker/my.cnf:/etc/mysql/conf.d/.my.cnf:ro
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
